export interface Product {
    id: number;
    name: string;
    category: string;
    price: number;
    image: string;
    type: string;
    occasion: string;
    code: string;
    availability: "In Stock" | "Out of Stock";
    grossWeight: string;
    netWeight: string;
    description?: string;
}

export const products: Product[] = [
    // Rings (1-10)
    {
        id: 1,
        name: "Royal Diamond Ring",
        category: "Rings",
        price: 45000,
        image: "/images/rings.jpg",
        type: "Diamond",
        occasion: "Wedding",
        code: "PG-R-001",
        availability: "In Stock",
        grossWeight: "4.50g",
        netWeight: "4.20g",
    },
    {
        id: 2,
        name: "Classic Gold Band",
        category: "Rings",
        price: 15000,
        image: "/images/rings.jpg",
        type: "Gold",
        occasion: "Daily Wear",
        code: "PG-R-002",
        availability: "In Stock",
        grossWeight: "3.00g",
        netWeight: "3.00g",
    },
    {
        id: 3,
        name: "Platinum Solitaire",
        category: "Rings",
        price: 55000,
        image: "/images/rings.jpg",
        type: "Platinum",
        occasion: "Engagement",
        code: "PG-R-003",
        availability: "In Stock",
        grossWeight: "3.80g",
        netWeight: "3.50g",
    },
    {
        id: 4,
        name: "Ruby Gemstone Ring",
        category: "Rings",
        price: 25000,
        image: "/images/rings.jpg",
        type: "Gemstone",
        occasion: "Party",
        code: "PG-R-004",
        availability: "Out of Stock",
        grossWeight: "3.20g",
        netWeight: "2.80g",
    },
    {
        id: 5,
        name: "Emerald Gold Ring",
        category: "Rings",
        price: 30000,
        image: "/images/rings.jpg",
        type: "Gold",
        occasion: "Festival",
        code: "PG-R-005",
        availability: "In Stock",
        grossWeight: "3.50g",
        netWeight: "3.10g",
    },
    {
        id: 6,
        name: "Vintage Diamond Ring",
        category: "Rings",
        price: 60000,
        image: "/images/rings.jpg",
        type: "Diamond",
        occasion: "Wedding",
        code: "PG-R-006",
        availability: "In Stock",
        grossWeight: "5.00g",
        netWeight: "4.60g",
    },
    {
        id: 7,
        name: "Rose Gold Stackable",
        category: "Rings",
        price: 12000,
        image: "/images/rings.jpg",
        type: "Gold",
        occasion: "Daily Wear",
        code: "PG-R-007",
        availability: "In Stock",
        grossWeight: "2.50g",
        netWeight: "2.50g",
    },
    {
        id: 8,
        name: "Sapphire Cocktail Ring",
        category: "Rings",
        price: 40000,
        image: "/images/rings.jpg",
        type: "Gemstone",
        occasion: "Party",
        code: "PG-R-008",
        availability: "In Stock",
        grossWeight: "4.00g",
        netWeight: "3.60g",
    },
    {
        id: 9,
        name: "Platinum Love Band",
        category: "Rings",
        price: 35000,
        image: "/images/rings.jpg",
        type: "Platinum",
        occasion: "Anniversary",
        code: "PG-R-009",
        availability: "In Stock",
        grossWeight: "3.20g",
        netWeight: "3.20g",
    },
    {
        id: 10,
        name: "Antique Gold Ring",
        category: "Rings",
        price: 28000,
        image: "/images/rings.jpg",
        type: "Gold",
        occasion: "Festival",
        code: "PG-R-010",
        availability: "Out of Stock",
        grossWeight: "4.80g",
        netWeight: "4.80g",
    },

    // Necklaces (11-20)
    {
        id: 11,
        name: "Bridal Gold Choker",
        category: "Necklaces",
        price: 120000,
        image: "/images/necklaces.jpg",
        type: "Gold",
        occasion: "Wedding",
        code: "PG-N-011",
        availability: "In Stock",
        grossWeight: "25.00g",
        netWeight: "25.00g",
    },
    {
        id: 12,
        name: "Diamond Pendant Chain",
        category: "Necklaces",
        price: 45000,
        image: "/images/necklaces.jpg",
        type: "Diamond",
        occasion: "Daily Wear",
        code: "PG-N-012",
        availability: "In Stock",
        grossWeight: "8.00g",
        netWeight: "7.80g",
    },
    {
        id: 13,
        name: "Emerald Necklace",
        category: "Necklaces",
        price: 85000,
        image: "/images/necklaces.jpg",
        type: "Gemstone",
        occasion: "Party",
        code: "PG-N-013",
        availability: "In Stock",
        grossWeight: "15.00g",
        netWeight: "14.20g",
    },
    {
        id: 14,
        name: "Platinum Chain",
        category: "Necklaces",
        price: 55000,
        image: "/images/necklaces.jpg",
        type: "Platinum",
        occasion: "Daily Wear",
        code: "PG-N-014",
        availability: "In Stock",
        grossWeight: "10.00g",
        netWeight: "10.00g",
    },
    {
        id: 15,
        name: "Temple Jewellery Set",
        category: "Necklaces",
        price: 150000,
        image: "/images/necklaces.jpg",
        type: "Gold",
        occasion: "Festival",
        code: "PG-N-015",
        availability: "Out of Stock",
        grossWeight: "30.00g",
        netWeight: "30.00g",
    },
    {
        id: 16,
        name: "Layered Gold Chain",
        category: "Necklaces",
        price: 35000,
        image: "/images/necklaces.jpg",
        type: "Gold",
        occasion: "Party",
        code: "PG-N-016",
        availability: "In Stock",
        grossWeight: "12.00g",
        netWeight: "12.00g",
    },
    {
        id: 17,
        name: "Solitaire Necklace",
        category: "Necklaces",
        price: 65000,
        image: "/images/necklaces.jpg",
        type: "Diamond",
        occasion: "Engagement",
        code: "PG-N-017",
        availability: "In Stock",
        grossWeight: "9.50g",
        netWeight: "9.20g",
    },
    {
        id: 18,
        name: "Ruby Bead Necklace",
        category: "Necklaces",
        price: 22000,
        image: "/images/necklaces.jpg",
        type: "Gemstone",
        occasion: "Casual",
        code: "PG-N-018",
        availability: "In Stock",
        grossWeight: "18.00g",
        netWeight: "16.50g",
    },
    {
        id: 19,
        name: "Kundan Polki Set",
        category: "Necklaces",
        price: 95000,
        image: "/images/necklaces.jpg",
        type: "Gold",
        occasion: "Wedding",
        code: "PG-N-019",
        availability: "In Stock",
        grossWeight: "22.00g",
        netWeight: "20.50g",
    },
    {
        id: 20,
        name: "Mangalsutra Design",
        category: "Necklaces",
        price: 48000,
        image: "/images/necklaces.jpg",
        type: "Gold",
        occasion: "Daily Wear",
        code: "PG-N-020",
        availability: "In Stock",
        grossWeight: "14.00g",
        netWeight: "13.80g",
    },

    // Earrings (21-30)
    {
        id: 21,
        name: "Diamond Studs",
        category: "Earrings",
        price: 25000,
        image: "/images/earrings.jpg",
        type: "Diamond",
        occasion: "Daily Wear",
        code: "PG-E-021",
        availability: "In Stock",
        grossWeight: "2.50g",
        netWeight: "2.30g",
    },
    {
        id: 22,
        name: "Gold Jhumkas",
        category: "Earrings",
        price: 35000,
        image: "/images/earrings.jpg",
        type: "Gold",
        occasion: "Festival",
        code: "PG-E-022",
        availability: "In Stock",
        grossWeight: "6.00g",
        netWeight: "6.00g",
    },
    {
        id: 23,
        name: "Chandbali Earrings",
        category: "Earrings",
        price: 45000,
        image: "/images/earrings.jpg",
        type: "Gemstone",
        occasion: "Wedding",
        code: "PG-E-023",
        availability: "In Stock",
        grossWeight: "8.50g",
        netWeight: "8.00g",
    },
    {
        id: 24,
        name: "Platinum Drops",
        category: "Earrings",
        price: 30000,
        image: "/images/earrings.jpg",
        type: "Platinum",
        occasion: "Party",
        code: "PG-E-024",
        availability: "In Stock",
        grossWeight: "4.00g",
        netWeight: "4.00g",
    },
    {
        id: 25,
        name: "Ruby Studs",
        category: "Earrings",
        price: 18000,
        image: "/images/earrings.jpg",
        type: "Gemstone",
        occasion: "Daily Wear",
        code: "PG-E-025",
        availability: "Out of Stock",
        grossWeight: "2.20g",
        netWeight: "1.90g",
    },
    {
        id: 26,
        name: "Temple Jhumkas",
        category: "Earrings",
        price: 42000,
        image: "/images/earrings.jpg",
        type: "Gold",
        occasion: "Festival",
        code: "PG-E-026",
        availability: "In Stock",
        grossWeight: "7.50g",
        netWeight: "7.50g",
    },
    {
        id: 27,
        name: "Diamond Hoops",
        category: "Earrings",
        price: 55000,
        image: "/images/earrings.jpg",
        type: "Diamond",
        occasion: "Party",
        code: "PG-E-027",
        availability: "In Stock",
        grossWeight: "5.50g",
        netWeight: "5.20g",
    },
    {
        id: 28,
        name: "Pearl Drop Earrings",
        category: "Earrings",
        price: 12000,
        image: "/images/earrings.jpg",
        type: "Gemstone",
        occasion: "Daily Wear",
        code: "PG-E-028",
        availability: "In Stock",
        grossWeight: "3.50g",
        netWeight: "3.00g",
    },
    {
        id: 29,
        name: "Bridal Earring Set",
        category: "Earrings",
        price: 85000,
        image: "/images/earrings.jpg",
        type: "Gold",
        occasion: "Wedding",
        code: "PG-E-029",
        availability: "In Stock",
        grossWeight: "12.00g",
        netWeight: "12.00g",
    },
    {
        id: 30,
        name: "Sui Dhaga Earrings",
        category: "Earrings",
        price: 22000,
        image: "/images/earrings.jpg",
        type: "Gold",
        occasion: "Daily Wear",
        code: "PG-E-030",
        availability: "In Stock",
        grossWeight: "3.80g",
        netWeight: "3.80g",
    },

    // Bracelets (31-40)
    {
        id: 31,
        name: "Gold Bangle Set",
        category: "Bracelets",
        price: 65000,
        image: "/images/bracelets.jpg",
        type: "Gold",
        occasion: "Wedding",
        code: "PG-B-031",
        availability: "In Stock",
        grossWeight: "15.00g",
        netWeight: "15.00g",
    },
    {
        id: 32,
        name: "Diamond Tennis Bracelet",
        category: "Bracelets",
        price: 95000,
        image: "/images/bracelets.jpg",
        type: "Diamond",
        occasion: "Party",
        code: "PG-B-032",
        availability: "In Stock",
        grossWeight: "8.00g",
        netWeight: "7.50g",
    },
    {
        id: 33,
        name: "Platinum Cuff",
        category: "Bracelets",
        price: 45000,
        image: "/images/bracelets.jpg",
        type: "Platinum",
        occasion: "Daily Wear",
        code: "PG-B-033",
        availability: "Out of Stock",
        grossWeight: "10.00g",
        netWeight: "10.00g",
    },
    {
        id: 34,
        name: "Gemstone Bracelet",
        category: "Bracelets",
        price: 28000,
        image: "/images/bracelets.jpg",
        type: "Gemstone",
        occasion: "Festival",
        code: "PG-B-034",
        availability: "In Stock",
        grossWeight: "6.50g",
        netWeight: "6.00g",
    },
    {
        id: 35,
        name: "Traditional Kadas",
        category: "Bracelets",
        price: 75000,
        image: "/images/bracelets.jpg",
        type: "Gold",
        occasion: "Wedding",
        code: "PG-B-035",
        availability: "In Stock",
        grossWeight: "20.00g",
        netWeight: "20.00g",
    },
    {
        id: 36,
        name: "Charm Bracelet",
        category: "Bracelets",
        price: 18000,
        image: "/images/bracelets.jpg",
        type: "Gold",
        occasion: "Daily Wear",
        code: "PG-B-036",
        availability: "In Stock",
        grossWeight: "5.00g",
        netWeight: "5.00g",
    },
    {
        id: 37,
        name: "Rose Gold Bangle",
        category: "Bracelets",
        price: 32000,
        image: "/images/bracelets.jpg",
        type: "Gold",
        occasion: "Party",
        code: "PG-B-037",
        availability: "In Stock",
        grossWeight: "8.50g",
        netWeight: "8.50g",
    },
    {
        id: 38,
        name: "Men's Gold Bracelet",
        category: "Bracelets",
        price: 55000,
        image: "/images/bracelets.jpg",
        type: "Gold",
        occasion: "Daily Wear",
        code: "PG-B-038",
        availability: "In Stock",
        grossWeight: "12.00g",
        netWeight: "12.00g",
    },
    {
        id: 39,
        name: "Diamond Kada",
        category: "Bracelets",
        price: 110000,
        image: "/images/bracelets.jpg",
        type: "Diamond",
        occasion: "Wedding",
        code: "PG-B-039",
        availability: "In Stock",
        grossWeight: "18.00g",
        netWeight: "17.00g",
    },
    {
        id: 40,
        name: "Evil Eye Bracelet",
        category: "Bracelets",
        price: 15000,
        image: "/images/bracelets.jpg",
        type: "Gemstone",
        occasion: "Daily Wear",
        code: "PG-B-040",
        availability: "In Stock",
        grossWeight: "4.00g",
        netWeight: "3.80g",
    },
];

export function getProductById(id: number): Product | undefined {
    return products.find((product) => product.id === id);
}
